name: os_express_flutter
description: "OS Express - Sistema para Ordens de Serviço, Orçamentos e Vendas"
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.0
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Image & Camera
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  
  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.4
  
  # File & Storage
  path_provider: ^2.1.4
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.0
  http: ^1.2.2
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.5.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
